version: '3'

services:
  php80:
    build: docker/php80
    volumes:
      - ./:/var/www
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1

  php83:
    build: docker/php83
    volumes:
      - ./:/var/www
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
